# Generated by Django 5.1.7 on 2025-04-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0005_settings_always_keep_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
