# Generated by Django 5.1.7 on 2025-03-27 22:48

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(help_text='شماره تماس باید به فرمت +989123456789 باشد.', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با +98 شروع شده و شامل ۱۰ رقم بعدی باشد.', regex='^\\+98[0-9]{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ایمیل باید با حروف انگلیسی شروع شده و دامنه @gmail.com داشته باشد.', regex='^[a-zA-Z][a-zA-Z0-9_.]*@gmail\\.com$')])),
                ('username', models.CharField(blank=True, help_text='نام کاربری باید با حروف انگلیسی شروع شده و شامل اعداد، نقطه و آندرلاین باشد.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='نام کاربری باید با حروف انگلیسی شروع شود و فقط شامل حروف، اعداد، نقطه و آندرلاین باشد.', regex='^[a-zA-Z][a-zA-Z0-9_.]*$')])),
                ('profile_photo', models.ImageField(blank=True, default='profile_pics/person.png', help_text='تصویر پروفایل خود را انتخاب کنید', null=True, upload_to='profile_pics/')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='album_photos/person.png', upload_to='album_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_photo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
